### ISSUE TITLE
New Visualization: Elephant Factor 

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/Rappel#109]
**Please describe the background and context for this new visualization**
The minimum number of companies whose employees perform a parameterizable definition of the total percentage of commits in a software repository is a project's 'elephant factor'. For example, one common filter is to say 50% of the commits are performed by n companies and that is the elephant factor.

**Describe the perspective you'd like the final visual to give**

**Describe the acceptance criteria for the issue and visualization to be complete**
https://chaoss.community/metric-elephant-factor/

**Additional context**
This will have to wait until we have a better understanding of organizational diversity

**REMINDER:** 
Before a visualization issue can be closed,there must be clear documentation on the notebook of the decisions made at each step and the "why."

**Comment by christinaexyou** [comment]
@JamesKunstle Please assign me to this issue.

**Comment by JamesKunstle** [comment]
@cdolfi what closes this issue? the affiliations page?

**Comment by cdolfi** [comment]
@JamesKunstle Yes i should have added in the comments
