### ISSUE TITLE
Augurface-ability to load repos/orgs directly

### ISSUE THREAD

**Issue by cdolfi** [oss-aspen/Rappel#141]
There is current work to put Augurface(UI/API to load repos/orgs into augur instance) on a open shift instance for are use. Currently @sgoggins and @mscherer are working through the bugs to make this happen 

Update on this one: We are locking down some controls we decided we want to accomplish this task through these steps. 

1. Login Full Circle
 - [ ] (H) [AI: Sean] First Step: Make sure an https instance can log in through augur on HTTP  
 - [ ] (M) [AI: Sean: Figure out if it works with https] Second step: Https on Augur server
 - [ ] (H) Login verification (like some email sent to validate the email exists at least)
     - [ ] (H) [AI: John] Make it so a user needs to link their user account to a GitHub account. 
     - [ ] (M) Validate that the email exists (or an alternative would be to rely on GitHub OAUTH)
         - [ ] Setup smtp
         - [ ] Send an email with the validation code
         - [ ] Only rights once they enter the code
     - [ ] (H) [AI: John/Andrew/Isaac]: Set up the admin portal for user management and profile update access. 
     - [ ] Could login creation notify somebody that a new user has been created?
     - [ ] Possibly a “new login approval flow”
  - [ ] A few login flow updates to make logout easier and changing your user repo group from the main page transparent within Augur. Ideally, there should be an API so 8Knot can get the user’s repo groups and change them.

**Comment by cdolfi** [comment]
@mscherer if there is any details miss/misrepresented please edit as necessary

**Comment by mscherer** [comment]
S9, right now, what block is the database being down, @duck-rh installed a new server with more disks, but I guess we need the rest of the installation (but tomorrow is a day off in japan, so it will be on monday)

**Comment by cdolfi** [comment]
@mscherer the database is up and running!

**Comment by cdolfi** [comment]
@mscherer @sgoggins tagging both of yall here to communicate on updates/blocks on this task

**Comment by mscherer** [comment]
So, I was looking at deploying the docker container on the new server, so I wrote a github workflow for that ( https://github.com/chaoss/augur/pull/1695 ), but seems it fail due to the frontend not building. 

The plan was to host official container on github, and just deploy them on the server, seems easier and cleaner.

**Comment by sgoggins** [comment]
@mscherer : I see the build issue. Docker is misbehaving with the /frontend container.  We don't have it building the augurface/ directory in a container right now. That's what is most important right now, correct?

**Comment by mscherer** [comment]
No, I was trying to build the backend to deploy on the new server. Since the old server disk was full, we reinstalled on a new system with more space, but augur itself is missing, and while on it, I am trying to add it on the ansible setup, or at least, as much as possible (as we also can't give access to it due to passwords, etc)

Using the existing container looked like a better way to deploy (no need to rewrite the installation instructions in ansible just for us), but since there was no official image, I figured I could add one (and later realized I could also port the travis CI to github actions). 

So the backend is for now what I look for. The frontend too, but I got it working on Openshift on friday (I think), so I guess that's some weird mismatch version, or something missing for later.

**Comment by sgoggins** [comment]
@mscherer : What do you need from us next? Also, do you know how to default the docker container to `public` ... GitHub has it set to `private` right now.

**Comment by sgoggins** [comment]
@mscherer : Is there anything I can do to help this one along ?

**Comment by cdolfi** [comment]
@mscherer How is the rest of the deployment going?

**Comment by sgoggins** [comment]
OK.

Please let me know if there is anything I can do to help.

Sean

*Sean P. Goggins*
*Professor, Electrical Engineering and Computer Science*
*Missouri*


*‌URL: http://www.seangoggins.net <http://www.seangoggins.net>‌*
(414) 485-5673‬

*2021 Journal of the Association for Information Systems and Technology
Best Paper Award Winner with Josh Introne, Bryan Semaan, and Ingrid
Erikson:*
https://www.asist.org/programs-services/awards-honors/best-jasist-paper-award/jasist-recipients/
for "Designing Sustainable Online Support: Examining the Effects of Design
Change in Forty-Nine Online Health Support Communities”

*Linux Foundation CHAOSS Project *Founding Board Member:  URL:
http://chaoss.community (for open source health metrics) [Sloan Foundation,
Ford Foundation, Reynolds School of Journalism]
*Linux Foundation: CHAOSS Augur Maintainer*,
https://github.com/chaoss/augur [Sloan
Foundation, National Science Foundation]
*Co-Creator, Mission Hydro Sci* https://mhs.misouri.edu [US Department of
Education]

*Research Lab Links:*
1. https://www.augurlabs.io [Sloan Foundation, National Science Foundation,
Ford Foundation, Reynolds School of Journalism]
2. https://linuxfoundation.org
3. https://ischool.syr.edu/joshua-introne/

"The only phrase I’ve ever disliked is, ‘Why, we’ve always done it that
way.’ I always tell young people, ‘Go ahead and do it. You can always
apologize later.” — Grace Hopper

"In real open source, you have the right to control your own destiny.”
— Linus Torvalds

**Comment by cdolfi** [comment]
lets see what @sgoggins has to say. I have a meeting with him tomorrow and I can point it out

**Comment by sgoggins** [comment]
@cdolfi : I have done some work on the dependencies. @mscherer : Does building `augur/frontend` container make the `augur/augurface` loading interface available for you then? It did not used to. Would it be more useful to provide an `augurface` container?

**Comment by sgoggins** [comment]
@mscherer : The PR I just merged looked to have "Frontend" in it, but not Augurface. Is that your intention right now? Or are we going to build a different container for Augurface?

**Comment by sgoggins** [comment]
@mscherer : I got through the errors and merged it. The one was a *very* obtuse little versioning issue for one library. 

@cdolfi : Augurface is merged as a functional Docker container thanks to @mscherer ... Now we need to test it in order to close this issue.

**Comment by cdolfi** [comment]
@sgoggins tagging for visibility and sounds good! Keep us updated

**Comment by cdolfi** [comment]
closing as augurface is up and running

**Comment by cdolfi** [comment]
@mscherer is this good to close?

**Comment by cdolfi** [comment]
@mscherer so what exactly needs to be done to close this?

**Comment by sgoggins** [comment]
Update on this one: We are locking down some controls we decided we want to accomplish this task through these steps. 
1.	Login Full Circle
	a.	(H) [AI: Sean] First Step: Make sure an https instance can log in through augur on http  
	b.	(M) [AI: Sean: Figure out if it works with https] Second step: Https on Augur server 
	c.	(H) Login verification (like some kind of email sent to validate the email exists at least)
		i.	(H) [AI: John] Make it so a user needs to link their user account to a GitHub account. 
		ii.	(M) Validate that the email exists (or an alternative would be to rely on GitHub OAUTH)
			1.	Setup smtp
			2.	Send an email with validation code
			3.	Only rights once they enter the code
		iii.	(H) [AI: John/Andrew/Isaac]: Set up the admin portal for user management and profile update access. 
		iv.	Could login creation notify somebody that a new user has been created?
		v.	Possibly a “new login approval flow”
	d.	A few login flow updates to make logout easier and changing your user repo group from the main page transparent within Augur. Ideally, there should be an API so 8Knot can get the user’s repo groups and change them.

**Comment by cdolfi** [comment]
Closing as we now can load projects from augur ui and its connected to the 8knot app🎉
