### ISSUE TITLE
Test the graph algorithms on other well known OSPO ecosystems

### ISSUE THREAD

**Issue by hemajv** [oss-aspen/Rappel#184]
In #174, we applied the PageRank and Betweenness Centrality algorithms on Kubernetes, Docker and OpenShift repos, fetching data during the time range of 2011-2014 (emergence of OpenShift). These algorithms were able to detect the closeness of the Kubernetes and Docker communities in relation to the OpenShift repos. The algorithms helped prove our hypothesis that closeness between already "well-known" (kubernetes, docker) repos can reveal emerging communities (OpenShift). We would like to test out the same methodology to some of the known OSPO ecosystems.

**Acceptance Criteria**:

- [x] Identify repo sets of commonly known OSPO ecosystems
- [x] Apply the PageRank and Betweenness Centrality algorithms to detect emerging communities
- [x] Visualize the results on graphs/charts for explainability

**Comment by bproffitt** [comment]
Okay, I would suggest:
Apache Kafka https://github.com/apache/kafka
Linux kernel https://github.com/torvalds/linux
Sigstore https://github.com/sigstore
