### ISSUE TITLE
Literature: Definition of Contributor Levels

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#188]
How can we categorize a repository's contributors?
e.g. 
Core, Active, Peripheral.

Find support in the literature for operationalizations of contributor categorization either by statistical or network strategies.

The goal is to be able to identify contributors by their respective roles of contribution. This will help us operationalize health metrics that involve intra-project communication, e.g. "do the core contributors do a good job of keeping track of up-and-coming contributors or are they very insulated?"

Two ways of doing this are: 
(1) Social network centrality measurements.
(2) Statistical strategies, e.g. "the smallest number of contributors who make up 80% of the work are the cores."

This task involves researching different ways to identify contributor category and planning how to implement the categorization on a live network of Ansible contributors. For now, we'll only look at a single repo at a time.

**Comment by mariashev** [comment]
Understanding core vs peripheral developer definitions

**Core developers** - play an essential role in developing the system architecture and forming the general leadership structure, and they have substantial, long-term involvement. 

**Peripheral developers** - typically involved in bug fixes/small enhancements, and they have irregular or short-term involvement.

**Core dev categorizing Intuition:** 
Count-based:
> - 80th percentile (Zipf distribution - typically the top 20% of contributors are responsible for 80% of the contributions)
> - higher commit count, more frequent contributions 
> - higher lines of code counts

Network-based:
(better reflection of developer perception)
> - degree centrality - core developers should have a larger degree than peripheral developers (more connections to more contributors, more connections to other core members) 
> - eigenvector centrality - core developers should occupy globally central positions in the developer network
> - hierarchy - core developers should have a high degree and low clustering coefficient, placing them in the upper region of the hierarchy (vice versa for peripheral)
> - role stability - core developers' stability in the developer network should be be higher than for peripheral developers
> - block model - expected pattern: P(core-core) > P(core-peripheral) > P(peripheral-peripheral)

Note - developer roles can change over time, account for this by using sliding window!

[Source](https://drive.google.com/file/d/19WdPBmpEdnU76aVnwOEnY8YtK8extM7C/view)

**Comment by mariashev** [comment]
**Validating assigned contributor roles:** 

Social network centrality - difficult to identify threshold (degree threshold for core developer node) 

Instead: implement statistical strategies first, compile a list of cntrb_ids classified as 'core developers' for each strategy (core = smallest # contributors who make up 80% work/commits/prs etc). 
   →  Then visualize network, identify nodes with highest degrees and compare with results from statistical strats. (Use this to 
  identify an optimal degree threshold)

**Comment by mariashev** [comment]
Finding Core contributors via count-based operations: 
https://colab.research.google.com/drive/1LWaNAHcIYl_aRCdqGDhklJ39aMUaaByZ#scrollTo=PfSUreCvg4qA

**Comment by oindrillac** [comment]
Awesome work @mariashev! Can we add this notebook to the graph analysis folder on the repo as well? So we can collaborate better

**Comment by cdolfi** [comment]
@JamesKunstle @mariashev Can this issue be closed?

**Comment by JamesKunstle** [comment]
@mariashev @cdolfi this issue is useful because it has our thoughts on the Active v. Peripheral v. Core question but I think it can be closed because we're not working on it anymore, and we've made some downstream decisions.
