### ISSUE TITLE
Growth of core contributor base over time

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#189]
Given that we know which contributors are considered 'Core' (or some proxy of core), how does the number of core developers change over time?

**Comment by cdolfi** [comment]
@mariashev @JamesKunstle Is this ready to be closed?

**Comment by JamesKunstle** [comment]
@mariashev I think this is sorta done because your current work shows the trend of the number of 'core' contributors over time but I'm also seeing that the number doesn't change, which I think is because it's a percentage threshold. What do you think?

**Comment by mariashev** [comment]
@cdolfi @JamesKunstle agreed, let's close it
