### ISSUE TITLE
Model contributor connectivity as a naive graph

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#191]
Even a simple mapping of contributors is pretty interesting, and having accomplished this sets us up for success for future experiments.

Connect contributors if:
1. They've created (committed, authored) a commit together,
2. They've participated in an issue thread together,
3. They've participated in the same PR message series together,
4. One has reviewed the other's PR.

We can start by assuming that edges are of weight 1. This may open a following question
about assigning edge weights by relationship depth (commenting on the same issue may carry less value than reviewing a PR or co-creating a commit).

**Comment by oindrillac** [comment]
The notebook looks great! @mariashev @JamesKunstle Can we add this to the graph analysis folder on the repo? This will form foundation for a lot of what we're looking into. Dont want to duplicate work that we've already accomplished 🙂

**Comment by mariashev** [comment]
Thank you @oindrillac Yes, absolutely! I need to make some changes but I can make a PR by the end of this week

**Comment by oindrillac** [comment]
Great, thanks! @mariashev
