### ISSUE TITLE
Make node sizes proportional to in-degree

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#196]
Identify important nodes in the network by having the size of the node in the networkX rendering by proportional to the number of nodes that they're connected to, or by the sum of the edge weights that they participate in. 

May need to do sum of log(edge weights) or something, or log(sum(log(edge weights)))

**Comment by oindrillac** [comment]
We modify node sizes based on some function of the number of nodes it is connected to (Pagerank), or how many it lies in the path of (betweenness centrality). NetworkX lets us use custom node sizing based on these rankings. You can see [notebook](https://github.com/oss-aspen/Rappel/blob/main/notebooks/graph_analysis/graph_inference.ipynb) for how we are doing that for project nodes

**Comment by mariashev** [comment]
Followed similar strategy used in [graph-analysis notebook](https://github.com/oss-aspen/Rappel/blob/main/notebooks/graph_analysis/graph_inference.ipynb) -> node size based on betweenness centrality. Values normalized, added small term to account for zero values. 

Code: 

    # get centrality values for node sizes
    centrality = nx.betweenness_centrality(G1)
    min_centrality = min(centrality.values())
    max_centrality = max(centrality.values())
    
    # rescale 
    norm_centrality = {node: (centrality[node] - min_centrality + 0.1) / (max_centrality - min_centrality + 0.1)
                             for node in G1.nodes()} # +0.1 to eliminate zero values
    node_sizes = [v * 100 for v in norm_centrality.values()] # adjust node size based on centrality 

Notebook: https://colab.research.google.com/drive/17hDW-UpuX33RD2ImlnCtg8R6mWwQmSoC#scrollTo=aTha2ik2FbZx
