### ISSUE TITLE
Investigate network algorithm solutions to contributor levels

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#197]
Network centrality might be interesting?
Page-rank?
Look at Oindrilla and Hema's work on project network results in the Rappel repo for inspiration.

**Comment by oindrillac** [comment]
Some takeaways from https://drive.google.com/drive/folders/1VUDPWJCfjB1WJQeH0ajUge0B3MQF-IF9
Contributor GCPs (Global centrality patterns) using  the SNA properties of
- Degree Centrality (Dc), 
- Betweenness Centrality (Bc), and
- Closeness Centrality (Cc) for each OSS projects.

Using Kmeans (I/P params are DC, BC and CC)
Developers can be categorized into
- Reflexive level (more coordination - more actors)
- Plan level (less coordination -only core)
- Aware level (core developers & active devs)

**Comment by mariashev** [comment]
Evaluated network using Pagerank, Degree Centrality, Betweenness Centrality, and Closeness Centrality. 

Compared scores (normalized) for top 20 contributors from each algorithm. 
- 11 contributors appeared in all 4 top 20 lists. 
- 20 contributors appeared in 3/4 top 20 lists. 

![Image](https://user-images.githubusercontent.com/87496627/234399718-dd28c779-b16b-46d2-a109-933c36ec7818.png)

notebook: https://colab.research.google.com/drive/193jHnC_WXCO9UymOTNitbLhBW9LBvows#scrollTo=ry7Sk6CKENZf

**Comment by cdolfi** [comment]
Closed as in "done" column
