### ISSUE TITLE
Find influential nodes in connection to known nodes

### ISSUE THREAD

**Issue by oindrillac** [oss-aspen/Rappel#198]
Currently when answering the Qs: _Which amongst a list of "Other" projects interact closely with a list of "Known" projects in a weighted graph where projects are nodes and edges are connections_ , we use closeness centrality to identify the closest and central nodes in a network. 

While this returns nodes that are close to each other, this can be influenced by including heavily interconnected nodes in the "Other" category which may not be very important in connection to the Known projects. 

Replace closeness centrality with a more nuanced heuristic for finding influential nodes.

**Problem:** Based on closeness centrality  the closer the node is to other nodes, the more central it is. Thus, when we use closeness centrality to find nodes which are the most central in a network, the score is impacted by closely connected nodes within a certain group such as the "Other projects". 

**Possible Solution:** 

- As a first step, it would be valuable to identify the most central nodes amongst the which are known to us and starting from there identify the nodes which interact most closely with these known project nodes
- If we want to get nodes closest to the most centrally located known repositories (lets say in an industry or software vertical or an organization), we need to first find the most centrally located known projects on the network and then find the nodes from a certain category which are closest to it. 
- Since in this network representation, the edge weights represent the degree of connection, we need to find closest nodes based on the geometric distance using an algorithm such as A*, Djikstra's or Best First Search.

**Comment by JamesKunstle** [comment]
@oindrillac Is this closable?
