### ISSUE TITLE
Investigate weighting of relationship contributions

### ISSUE THREAD

**Issue by mariashev** [oss-aspen/Rappel#202]
Issue message co-appearance and PR review interactions shouldn't be considered equal to the DSN. 

Investigate how to operationalize a multi-level weighting of contributor interactions such that more involved relationships (co-committers, PR reviewers) are more closely related than message-thread-co-inhabitors. 

One possible lead: https://orbit.love/model/love/orbit-levels

Should also consider decay or relationship over time- old relationships should not subvert the importance of newly formed ones automatically.

**Comment by cdolfi** [comment]
Closed as in "done" column
