### ISSUE TITLE
Page rank contributors

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#205]
Run page rank algorithm on developer social network. 

Network considers relationships from mutual commit authorship, PR message threads, Issue message threads, and PR reviews. 

Goal is to identify, in order, the highest to lowest ranked contributors.

Weights of interactions ( co-committership, PR reviewing, etc.) should, for the time being, be naive. (all interactions should have a weight of 1.0)

**Comment by mariashev** [comment]
Notebook: https://colab.research.google.com/drive/193jHnC_WXCO9UymOTNitbLhBW9LBvows#scrollTo=y7BOZWtPTKja

Top 10 conributors based on pagerank (with naive weights):

1. 01012f1b-7f00-0000-0000-000000000000: Score 0.08243858925165543
2. 01000045-2400-0000-0000-000000000000: Score 0.07939057787454838
3. 01000c4d-d800-0000-0000-000000000000: Score 0.0701451505214677
4. 01000cc2-4b00-0000-0000-000000000000: Score 0.037363315745449786
5. 01000067-2300-0000-0000-000000000000: Score 0.028521744677016084
6. 01000e5a-0d00-0000-0000-000000000000: Score 0.021280848463192666
7. 01000099-ac00-0000-0000-000000000000: Score 0.016306323695686374
8. 01001c87-8900-0000-0000-000000000000: Score 0.015489393733754565
9. 01000331-5a00-0000-0000-000000000000: Score 0.014844764808603472
10. 010009ab-a500-0000-0000-000000000000: Score 0.012833322285940483

Will add this to adjacency matrix

**Comment by cdolfi** [comment]
Closed as in "done" column
