### ISSUE TITLE
Repos to be added to Augur

### ISSUE THREAD

**Issue by hemajv** [oss-aspen/Rappel#208]
We would like to have the following repos added to Augur:

https://github.com/aeraki-mesh/aeraki
https://github.com/project-akri/akri
https://github.com/cdk8s-team/cdk8s
https://github.com/dexidp/dex
https://github.com/ko-build/ko
https://github.com/pixie-io/pixie
https://github.com/bfenetworks/bfe
https://github.com/chaosblade-io/chaosblade
https://github.com/devspace-sh/devspace
https://github.com/krustlet/krustlet
https://github.com/kubescape/kubescape
https://github.com/kumahq/kuma
https://github.com/lima-vm/lima
https://github.com/openebs/openebs

cc @JamesKunstle @cdolfi

**Comment by cdolfi** [comment]
closing as these repos were added in on friday
