### ISSUE TITLE
Enrich contributor graph interface.

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#210]
(1) wrap network generation logic in a function
(2) parameterize the weights of different kinds of events
    (a) PR = 2.0, issue_message = 0.1, PR_message = 0.5, Commit = 1.0 as defaults.
(3) figure out how to apply decay per some time window. e.g. decay period and decay value.
(4) make contributor events an event-stream ordered by occurrence.

**Comment by mariashev** [comment]
1,2 done, decided to not go forward with time decay -> over time visualization instead

**Comment by cdolfi** [comment]
Closed as in "done" column
