### ISSUE TITLE
Supplement graph analysis of emergence of openshift with project growth trend metrics

### ISSUE THREAD

**Issue by oindrillac** [oss-aspen/Rappel#211]
Supplement network analysis for emergence of openshift from kubernetes with the trends in the growth of project over time (such as contributors, issues, project metrics forks etc). 
Explore if we can use the 8Knot dashboard for this or if we want to run queries directly within the notebooks.

(This is also a feedback that we received from presenting this session at [OSS NA](https://ossna2023.sched.com/event/1K5GO/discovering-emerging-open-source-communities-through-graphical-analysis-oindrilla-chatterjee-hema-veeradhi-red-hat-inc?iframe=no
))

**Comment by hemajv** [comment]
We can use the 8Knot dashboard for these as it showcases some of the community trend metrics over time: https://eightknot.osci.io/overview

**Comment by oindrillac** [comment]
closing as this was completed
