### ISSUE TITLE
Introduce weighted edge connections in the project focused graph networks

### ISSUE THREAD

**Issue by oindrillac** [oss-aspen/Rappel#216]
Introduce weighted edge connections in the project focused graph networks based on degree of participation of contributors based on work done in  https://github.com/oss-aspen/Rappel/issues/188 on the prominence of individuals in a community. 

Potential weighting ideas by @JamesKunstle:

- Importance of a mutual contributor is either the max of the importance of contributor across all communities or the avg- maybe weighted additionally by some variant or inverse of TF/IDF
- Weighted proportionally to recency as well, likely.

**Comment by JamesKunstle** [comment]
Assigned to @christinaexyou

**Comment by JamesKunstle** [comment]
Continuing discussion here: https://github.com/oss-aspen/Rappel/pull/236

**Comment by cdolfi** [comment]
should this be closed?
