### ISSUE TITLE
Community Dynamics Analysis

### ISSUE THREAD

**Issue by mariashev** [oss-aspen/Rappel#218]
**Implement feedback from dashboard demo:**
- [x] Event weight selection as sliders
- [x] Play/pause buttons for network graph
- [x] Implement threshold options
- [x] Add total contributors over time count to cardinality plot
- [x] Add legend for network graph 
- [x] Add plot explanations
- [x] Add comments to code

**Comment by cdolfi** [comment]
@mariashev Should this issue be closed?
