### ISSUE TITLE
Measuring a community's organizational diversity

### ISSUE THREAD

**Issue by JamesKunstle** [oss-aspen/Rappel#35]
## The gap to be addressed
Consensus must be achieved regarding which metrics describe the diversity of a community summarily from the Augur data that we have available.

## Prospective Ideas
We need to look at the fields that are indicative of a user's affiliation, e.g. email, groups, etc.

## Ideal steps
- [ ] Discuss which of the populated fields are likely to have this information,
- [ ] Agree upon the extraction protocol (e.g. regex, parsing),
- [ ] Discuss potential for expansion of ERD to fulfill this metric in the future.

**Comment by JamesKunstle** [comment]
Update: still waiting for Augur 'contributors', 'contributor aliases', and 'contributor affiliations' tables to become stable in order to move forward.

**Comment by cdolfi** [comment]
The update necessary to get this moving will be released tomorrow

**Comment by cdolfi** [comment]
Does Grimorelab sorting hat do anything to help with this? https://chaoss.github.io/grimoirelab/ https://github.com/chaoss/grimoirelab-sortinghat
